version: '3.7'

services:
  flask-database:
    container_name: flask-database
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=flask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    container_name: web
    image: flask_app
    restart: always
    ports:
      - 5000:5000
  proxy-server:
    container_name: nginx-server
    image: custom-nginx
    restart: always
    ports:
      - 80:80

volumes:
  postgres_data: {}