version: '3.7'

services:
  web:
    #build: web
    image: flask_appp
    restart: always
    ports:
      - 5000:5000
    networks:
      - flask_network
  proxy-server:
    #build: proxy-server
    image: custom-nginx
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=flask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  flask_network:

volumes:
  postgres_data: