# This file creates a Deployment and a Service for a Flask app in a Kubernetes cluster.
# The Deployment creates two replicas of a pod, each containing a container running the Flask app.
# The Service exposes the app to external traffic on port 5000.
# The pod container has a volume mount and environment variable and resources limits and reservations.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsgi-server
  namespace: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: local-monument-website
  template:
    metadata:
      labels:
        app: local-monument-website
        app.kubernetes.io/name: local-monument-website
    spec:
      containers:
        - name: wsgi-server
          image: jakubszuber/custom-gunicorn
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            reservations:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_DATABASE_URI
              value: "postgresql://admin:admin@flask-database:5432/flask_db"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wsgi-server
  namespace: vote
spec:
  selector:
    app: local-monument-website
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
