# This file creates Deployment and Service for a Nginx in a Kubernetes cluster (in the local-monument-website namespace).
# The Deployment creates one replica of a pod, with the single container that runs Nginx container.
# The Service exposes the proxy server to external traffic on port 80, and forwards traffic to target port 80
# on the selected pods.
# The pod container has an environment variable and resources limits and reservations.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-server
  namespace: local-monument-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-monument-website
  template:
    metadata:
      labels:
        app: local-monument-website
    spec:
      containers:
        - name: proxy-server
          image: jakubszuber/custom-nginx
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-server
  namespace: local-monument-website
spec:
  type: NodePort
  selector:
    app: local-monument-website
  ports:
    - port: 80
      targetPort: 80
      # Optional field
      # You can change the below value to have a different port exposed on your node
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
