apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: local-monument-website
  template:
    metadata:
      labels:
        app: local-monument-website
        app.kubernetes.io/name: local-monument-website
    spec:
      containers:
        - name: proxy-server
          image: custom-nginx
          resources:
            limits:
              cpu: 0.50
              memory: 256Mi
            reservations:
              cpu: 0.25
              memory: 128Mi
          ports:
            - containerPort: 80
          env:
            - name: WSGI_SERVER_URL
              value: "wsgi-server:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-server
spec:
  type: NodePort
  selector:
    app: local-monument-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
