# This file creates a ConfigMap resource definition for postgres-secret in a Kubernetes cluster (in the local-monument-website namespace).
# The data section contains the database name, user, and password for the flask_db database.

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: local-monument-website
  labels:
    app: local-monument-website
data:
  POSTGRES_DB: flask_db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
