# This file creates a Persistent Volume Claim, a StatefulSet, and a Service for a Postgres database in a Kubernetes cluster.
# The Persistent Volume Claim creates a storage of 1Gi
# The StatefulSet creates two replicas of a pod, each containing a container running the Postgres database.
# The Service exposes the Postgres database to internal traffic on port 5432 and forwards traffic to target port 5432 on the selected pods.
# The pod container has an environment variable and resources limits and reservations.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: local-monument-website
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-database
  namespace: local-monument-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: local-monument-website
  template:
    metadata:
      labels:
        app: local-monument-website
        app.kubernetes.io/name: local-monument-website
    spec:
      containers:
        - name: flask-database
          image: jakubszuber/custom-postgres
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: flask_db
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: flask-database
  namespace: local-monument-website
spec:
  selector:
    app: local-monument-website
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
