# This file creates a PersistentVolume resource definition for postgres-volume in a Kubernetes cluster (in the local-monument-website namespace).
# The spec section contains the storage class name, capacity, access modes, and host path information.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: local-monument-website
  labels:
    type: local
    app: local-monument-website
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql"
