# This file creates a PersistentVolumeClaim resource definition for postgres-volume-claim in a Kubernetes cluster (in the local-monument-website namespace).
# The spec section contains the storage class name, access modes, and storage resources request information.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: local-monument-website
  labels:
    app: local-monument-website
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
