# This file creates Deployment and Service for a PostgreSQL in a Kubernetes cluster (in the local-monument-website namespace).
# The Deployment creates one replica of a pod, with the single container that runs Postgres container.
# The Service exposes the deployment on a cluster-internal IP traffic on port 5432.
# The pod container has an environment variable and resources limits and reservations.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-database
  namespace: local-monument-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-monument-website
  template:
    metadata:
      labels:
        app: local-monument-website
    spec:
      containers:
        - name: flask-database
          image: postgres:15-alpine
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: flask-database
  namespace: local-monument-website
  labels:
    app: local-monument-website
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: local-monument-website
